home/urls.py
from home import views
from django.urls import path

app_name = 'home'

urlpatterns = [
    path('tabs/', views.index, name='index'),

    path('tabs/create_tabs/', views.create_tabs, name='create_tabs'),
    path('tabs/create_artist/', views.create_artist, name='create_artist'),
    path('tabs/artists/', views.artists, name='artists'),
    path('tabs/artists/<str:artist>/songs/', views.artist, name='artist'),
    path('tabs/artists/<str:artist>/songs/<str:song>/', views.song, name='song'),

    #user
    path('user/create/',views.register, name='register'),
    path('user/login/',views.login_view, name='login'),
    path('user/logout/',views.logout_view, name='logout'),
    path('user/update/',views.user_update, name='user_update'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('',include('home.urls')),
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('/user/login/')),  # Redireciona a raiz para /login/
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

class Style(models.Model):

    #Corrigir o erro do plural
    class Meta:
        verbose_name = 'Style'
        verbose_name_plural = 'Styles'

    name = models.CharField(max_length=50)
    show = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.name

class Instrument(models.Model):

    #Corrigir o erro do plural
    class Meta:
        verbose_name = 'Instrument'
        verbose_name_plural = 'Instruments'

    name = models.CharField(max_length=50)
    show = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.name
  
class Artist(models.Model):

    class Meta:
        verbose_name = 'Artist'
        verbose_name_plural = 'Artists'

    name = models.CharField(max_length=50)
    show = models.BooleanField(default=True)
    user = models.CharField(max_length=150,null=True,blank=True)
    
    def __str__(self) -> str:
        return self.name
    

class Song(models.Model):
    song_name = models.CharField(max_length=50)
    song_author = models.ForeignKey(Artist,on_delete=models.SET_NULL,null=True)
    show = models.BooleanField(default=True)
    yt_video = models.CharField(max_length=255, null=True, blank=True)
    audio = models.FileField(upload_to='Songs/', null=True, blank=True)
    tab = models.FileField(upload_to='Tabs/',null=True,blank=True)
    user = models.CharField(max_length=150,null=True,blank=True)
    style = models.ForeignKey(Style,on_delete=models.SET_NULL,blank=True,null=True)
    instrument = models.ForeignKey(Instrument,on_delete=models.SET_NULL,blank=True,null=True)

    class Meta:
        verbose_name = 'Song'
        verbose_name_plural = 'Songs'

    def __str__(self) -> str:
        return f'{self.song_name} {self.song_author}'

home/forms.py
from .models import *
from django import forms # type: ignore
from django.core.exceptions import ValidationError # type: ignore
from django.contrib.auth.forms import UserCreationForm # type: ignore
from django.contrib.auth.models import User # type: ignore



from django import forms
from .models import Song, Artist

from django import forms
from .models import Song, Artist

class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['song_name', 'song_author', 'yt_video', 'audio', 'tab', 'style', 'instrument']

    def __init__(self, *args, **kwargs):
        artist_queryset = kwargs.pop('artist_queryset', Artist.objects.none())
        super().__init__(*args, **kwargs)
        self.fields['song_author'].queryset = artist_queryset

class ArtistForm(forms.ModelForm):

    class Meta: 
        model = Artist
        fields = ('name',)


    def clean(self):
        return super().clean()


class RegisterForm(UserCreationForm):
    username = forms.CharField(required=True)  # Pode ser mantido, pois o campo `username` é obrigatório

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password1', 'password2')

home/views.py
from django.shortcuts import render,get_object_or_404,redirect
from home.models import Song,Artist
from django.core.paginator import Paginator
from django.urls import reverse 
from home.forms import SongForm
# Create your views here.

#Some random songs
def index(request):

    song = Song.objects.filter(show=True).order_by('-song_name')
    paginator = Paginator(song, 10)  # Show 10 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'title': 'Home',
        'page_obj':page_obj,
    }

    return render(request,'home/index.html',context)


#A single artist
def artist(request,artist):

    Artist = get_object_or_404(Song,pk=artist,show=True)

    context = {
        'contact':Artist,
        'title': Song.song_author
    }
    return render(
        request,
        'home/artist.html',
        context
        )


#List of all artists
def artists(request):

    artists = Artist.objects.filter(show=True).order_by('-name')
    paginator = Paginator(artists, 10)  # Show 10 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'artists':Artist,
        'title': 'Artists',
        'page_obj': page_obj
    }

    return render(
        request,
        'home/artists.html',
        context
        )


#list of songs by this artist
def songs(request, artist, song):

    artist = get_object_or_404(Artist.name, username=artist)

    song = get_object_or_404(Song.song_name, id=song, artist=artist)

    songs = Song.objects.filter(show=True).order_by('-id')
    paginator = Paginator(songs, 10)  # Show 10 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'artist': artist,
        'song': song,
        'title' : f'{Artist.name} - Songs',
        'page_obj': page_obj
    }

    return render(request, 'home/songs.html', context)

#A single song by this artist
def song(request, artist, song):

    artist = get_object_or_404(Artist.name, username=artist)

    song = get_object_or_404(Song.song_name, id=song, artist=artist)

    context = {
        'artist': artist,
        'song': song,
        'title' : f'{Artist.name} - {Song.song_name}'
    }

    return render(request, 'home/song.html', context)


#Create tabs
def create(request):

    form_action = reverse('home:create')

    if request.method == 'POST':

        form = SongForm(request.POST,request.FILES)

        context = {
            'title':'Create contact',
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            contact = form.save() #salvar os dados na base de dados

            return redirect('home:index',contact_id=contact.pk)
        
        return render(
            request,
            'home/create.html',
            context
            )
    
    context = {
                'title':'Create contact',
                'form': SongForm(),
                'form_action': form_action,
            }
    
    return render(
            request,
            'home/create.html',
            context
            )

home/views/home_forms.py
from django.shortcuts import render,get_object_or_404,redirect
from django.urls import reverse 
from home.forms import SongForm,ArtistForm
from home.models import Song,Artist
# Create your views here.


#Create tabs
from home.forms import SongForm, ArtistForm
from home.models import Song, Artist

def create_tabs(request):
    form_action = reverse('home:create_tabs')

    if not request.user.is_authenticated:
        return redirect('home:login')

    if request.method == 'POST':
        form = SongForm(request.POST, request.FILES, artist_queryset=Artist.objects.filter(user=request.user.username))

        context = {
            'title': 'Create Song',
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            new_song = form.save(commit=False)
            new_song.user = request.user.username
            new_song.save()

            return redirect('home:index')

        return render(
            request,
            'home/create_song.html',
            context
        )

    context = {
        'title': 'Create Song',
        'form': SongForm(artist_queryset=Artist.objects.filter(user=request.user.username)),
        'form_action': form_action,
    }

    return render(
        request,
        'home/create_song.html',
        context
    )


def create_artist(request):
    form_action = reverse('home:create_artist')

    if not request.user.is_authenticated:
        return redirect('home:login')

    if request.method == 'POST':
        form = ArtistForm(request.POST, request.FILES)

        context = {
            'title': 'Create Artist',
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            new_artist = form.save(commit=False)
            new_artist.user = request.user.username  
            new_artist.save() 

            return redirect('home:index')

        return render(
            request,
            'home/create_artist.html',
            context
        )

    context = {
        'title': 'Create Artist',
        'form': ArtistForm(),
        'form_action': form_action,
    }

    return render(
        request,
        'home/create_artist.html',
        context
    )

home/views/home_views.py
from django.shortcuts import render,get_object_or_404,redirect
from home.models import Song,Artist
from django.core.paginator import Paginator
from home.funcs import *

# Create your views here.

#Some random songs
def index(request):

    user_name = request.user.username

    if request.user.is_authenticated:

        song = Song.objects.filter(show=True,user=user_name).order_by('-song_name')
        paginator = Paginator(song, 10)  # Show 10 contacts per page.
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        context = {
            'title': 'Home',
            'page_obj':page_obj,
        }

        return render(request,'home/index.html',context)

    return redirect('home:login')


#A single artist
def artist(request,artist):

    user_name = request.user.username
        
    if request.user.is_authenticated:


        Artist_ = get_object_or_404(Artist,pk=artist,show=True)

        songs = Song.objects.filter(song_author=Artist_,show=True,user=user_name).order_by('-song_name')
        paginator = Paginator(songs, 10)  # Show 10 contacts per page.
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        context = {
            'Artist':Artist_,
            'title': Artist_.name,
            'page_obj': page_obj
        }
        
        return render(
            request,
            'home/artist.html',
            context
            )
    
    return redirect('home:login')


#List of all artists
def artists(request):
    if not request.user.is_authenticated:
        return redirect('home:login')

    user_name = request.user.username

    # Filtrar artistas criados pelo usuário autenticado
    artists = Artist.objects.filter(show=True, user=user_name).order_by('-name')

    paginator = Paginator(artists, 10)  # Paginação com 10 artistas por página
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'artists': artists,  # Passa o queryset filtrado
        'title': 'Artists',
        'page_obj': page_obj,  # Objeto da página atual
    }

    return render(request, 'home/artists.html', context)


#A single song by this artist
def song(request, artist, song):
        
    if request.user.is_authenticated:

        artist_obj = get_object_or_404(Artist, id=artist)

        song_obj = get_object_or_404(Song, id=song, song_author=artist_obj)


        context = {
            'artist': artist_obj,
            'song': song_obj,
            'title' : f'{artist_obj.name} - {song_obj.song_name}',
            'tabs': song_obj.tab
        }

        return render(request, 'home/song.html', context)
    
    return redirect('home:login')

home/views/user_forms.py
from django.shortcuts import render,redirect # type: ignore
from home.forms import RegisterForm # type: ignore
from django.contrib import messages # type: ignore
from django.contrib.auth.forms import AuthenticationForm # type: ignore
from django.contrib import auth # type: ignore
from django.contrib.auth import login as auth_login

def register(request):

    form = RegisterForm()   

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request,'Usuário logado')
            return redirect('home:login')

    context = {
        'form': form,
        'title': 'Register',
    }

    return render(request,'home/user/register.html',context)

def login_view(request):
    form = AuthenticationForm(request, data=request.POST if request.method == 'POST' else None)

    if request.method == 'POST':
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            messages.success(request, 'Logado com sucesso')
            return redirect('home:index')

        messages.error(request, 'Erro ao realizar login')

    context = {
        'form': form,
        'title': 'login',
    }
    return render(request, 'home/user/login.html', context)

def logout_view(request):

    auth.logout(request)

    return redirect('home:login')

def user_update(request):

    form = RegisterForm(instance=request.user)

    context = {
        'form': form,
        'title': 'Update User'
    }


    if request.method!='POST':
        return render(request,'home/user/update.html',context)

    form = RegisterForm(data=request.POST, isinstance=request.user)

    if not form.is_valid():
        return render(request,'home/user/update.html',context)
    
    form.save()

    return redirect('home:user_update')

home/templates/home/artist.html
{% extends "global/base.html" %}

{% block content %}
{% if page_obj %}

    <div class="responsive-table">
        <table class="contacts-table">

            <caption class="table-caption">
                Artist
                Name: {{title}}
            </caption>

            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">Song Name</th>
                    <th class="table-header">Audio</th>
                </tr>
            </thead>

            <tbody>
                {% for song in page_obj %}
                    <tr class="table">
                        <td class="table-cel">
                            <a class="table-link" href="{% url "home:song" song.song_author.id song.id %}">{{song.id}}</a>
                        </td>

                        <td class="table-cel">
                            {{song.song_name}}
                        </td>

                        <td class="table-cel">
                            {% if song.audio %}
                                <audio controls>
                                    <source src="{{ song.audio.url }}" type="audio/mpeg">
                                </audio>
                            {% else %}
                                No audio available
                            {% endif %}
                        </td>

                    </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>

{% else %}
<div class="single-contact">
    <h1 class="single-contact-name">
        No results
    </h1>
</div>
{% endif %}
{% endblock content %}

home/templates/home/artists.html
{% extends "global/base.html" %}

{% block content %}

{% if page_obj %}

    <div class="responsive-table">
        <table class="contacts-table">

            <caption class="table-caption">
                Artists
            </caption>

            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">Artist Name</th>
                </tr>
            </thead>

            <tbody>
                {% for artist in page_obj %}
                    <tr class="table">

                        <td class="table-cel">
                            <a class="table-link" href="{% url 'home:artist' artist.id %}">{{artist.name}}</a>
                        </td>

                    </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>

{% else %}
<div class="single-contact">
    <h1 class="single-contact-name">
        No results
    </h1>
</div>
{% endif %}
{% endblock content %}

home/templates/home/create_artist.html
{% extends "global/base.html" %}

{% block content %}
  <h1>Add artist</h1>
  
  <div class="form-wrapper">
    <h2>Artist</h2>
    
    <form 
      action="{{from_action}}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}

      <div class="form-content">

        {% for field in form %}
          <div class="form-group">
            <label for="{{field.id_for_label}}">{{field.label}}:</label>
            {{field}} {# 'São os inputs' #}
            {{field.errors}}
            {% if field.help_text %}
              <p class="help-text">{{field.help_text}}</p>
            {% endif %}
          </div>

          {% if field.name == 'picture' and field.value.url %}
            <div class="form-group"> 
                <img src="{{field.value.url}}" alt="">
            </div>
          {% endif %}
          
        {% endfor %}
      </div> 

      {% if form.non_field_errors %}
      <div class="form-content">
        <div class="form-group">
          <div class="messege error">
            {{form.non_field_errors}}
          </div>
        </div>
      </div>
      {% endif %}

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %}

home/templates/home/create_song.html
{% extends "global/base.html" %}

{% block content %}
  <h1>Add song</h1>
  
  <div class="form-wrapper">
    <h2>Song</h2>
    
    <form 
      action="{{from_action}}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <div class="form-content">

        {% for field in form %}
          <div class="form-group">
            <label for="{{field.id_for_label}}">{{field.label}}:</label>
            {{field}} {# 'São os inputs' #}
            {{field.errors}}
            {% if field.help_text %}
              <p class="help-text">{{field.help_text}}</p>
            {% endif %}
          </div>

          {% if field.name == 'picture' and field.value.url %}
            <div class="form-group"> 
                <img src="{{field.value.url}}" alt="">
            </div>
          {% endif %}
          
        {% endfor %}
      </div> 

      {% if form.non_field_errors %}
      <div class="form-content">
        <div class="form-group">
          <div class="messege error">
            {{form.non_field_errors}}
          </div>
        </div>
      </div>
      {% endif %}

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %}

home/templates/home/index.html
{% extends "global/base.html" %}
{% block content %}

{% if page_obj %}

    <div class="responsive-table">

        <h1>Some songs</h1>

        <table class="contacts-table">
            <caption class="table-caption">
            </caption>

            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">Song</th>
                    <th class="table-header">Artist</th>
                    <th class="table-header">Audio</th>
                </tr>
            </thead>

            <tbody>
                {% for song in page_obj %}
                    <tr class="table">

                        <td class="table-cel"> 
                            <a class="table-link" href="{% url "home:song" song.song_author.id song.id %}">{{song.song_name}}</a>
                        </td>

                        <td class="table-cel">
                            {{song.song_author}}
                        </td>

                        <td class="table-cel">
                            {% if song.audio %}
                                <audio controls id='music'>
                                    <source src="{{ song.audio.url }}" type="audio/mpeg">
                                    <source src="{{ song.audio.url }}" type="audio/wav">
                                    <source src="{{ song.audio.url }}" type="audio/ogg">
                                </audio>
                            {% else %}
                                No audio available
                            {% endif %}
                        </td>

                    </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>

{% else %}
<div class="single-contact">
    <h1 class="single-contact-name">
        No results
    </h1>
</div>
{% endif %}
{% endblock content %}

home/templates/home/song.html
{% extends "global/base.html" %}

{% block content %}
  <h1>Song</h1>
        
    <div class="form-content">

        <div class="form-group">
            <h2>
                Song name:
            </h2>
            {{song.song_name}}
            
        </div>

        <div class="form-group">
            <h2>
                Artist:
            </h2>
            {{song.song_author}}
        </div>

        <div class="form-group">
            <h2>
                Instrument:
            </h2>
            {{song.instrument}}
        </div>
        
        <div class="form-group">
            <h2>
                Yt tutorial:
            </h2>
            <a href="{{song.yt_video}}" target="_blank">{{song.yt_video}}</a>
        </div>

        <h2>
            Audio:
        </h2>
        {% if song.audio %}
            
            <audio controls id='music'>
                <source src="{{ song.audio.url }}" type="audio/mpeg">
                <source src="{{ song.audio.url }}" type="audio/wav">
                <source src="{{ song.audio.url }}" type="audio/ogg">
            </audio>
        {% else %}
            No audio availablea
        {% endif %}

        <div class="form-group">
            <h2>
                Song style:
            </h2>
            {{song.style}}
        </div>
           
        <h2>
            Tabs:
        </h2>
        {% if tabs %}
            <iframe src="{{ song.tab.url }}" width="1000" height="1000"></iframe>
        {% else %}
            No tabs available
        {% endif %}

    </div> 

{% endblock content %}